### ISSUE TITLE
could not install ubuntu 16.04

### ISSUE THREAD

**Issue by jonathanstrong** [yamins81/tabular#6]
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lxNTgC/tabular/setup.py", line 50, in <module>
        raise ImportError("distribute was not found and fallback to setuptools was not allowed")
    ImportError: distribute was not found and fallback to setuptools was not allowed
```

also tried running setup.py install in a cloned repo
python 2.7
new install of 16.04
just fyi

**Comment by dopatraman** [comment]
am also running into this issue, python 3.6

**Comment by brianjmurrell** [comment]
As am I on python 3.4 on CentOS 7.5 even when I get the latest version of _pip_.
